### PR TITLE
trying to improve win perf on cpu_windows.c

### PR DESCRIPTION
**Pull request by hilga007**

### CODE REVIEW

**Comment by CarterLi** [comment]
Randomly copied code won't make you a good programmer. Please don't do this.

Closing as spam.

**Comment by hilga007** [comment]
> Randomly copied code won't make you a good programmer. Please don't do this.
> 
> Closing as spam.

This is extremely arrogant, rude, ("randomly copying code") and "this is spam" --- this is the reason I am always too shy to try software development stuff. Many developers have a massive ego issue, you included. Please don't do this. 

I have advocated for replacing neofetch with fastfetch for (years?) since I first discovered it, asked for many feature requests (Vulkan version, detected graphics card versions, etc and was happy you integrated those ideas) -- and I was happy to recently find some repos like AntiX have it in their repos. 

I bought a "C for Absolute Beginners" Book w/eBook and web-based sample courses. I spent a log time taking notes in OneNote and Notepad++. 

The other day I decided to push past the anxiety to fork the project and add a few things. I couldn't see the difference unless I added a merge request (twice for some reason) and then went to bed because I had been "tinkering" on my favorite project and inspiration for learning. 

**My mistake: accidentally submitting them to you somehow. That's OK, whoops, looks like I made a mistake.**

But to call someone who is clearly new, who has clearly submitted suggestions in the past that you have implemented "spam and a bad developer" is just heart-crushing. 

**I made a mistake but your arrogance cannot see that, and does not want to help, it wants to criticize and be rude. (Oder vielliecht bistda nur Deutscher und diese "arroganz" ist nur Deutsch auf Englisch und stylisch ist nur bissel unhöflich?)**

Either way - this goes to show you that you can't judge a book by its cover. I really do wish to help and contribute and learn - to make something already fast, even faster. To learn C finally (C99 from my stepdad's old books is all I had at first) but I cannot afford the cost of university -- so my "spam" is just me attempting to put my ideas from Notepad++ into a single platform (GitHub) and from here, then test what might be wrong. 

I was ill yesterday so did not reply right away (panic attack from seeing the replies in my email inbox, then puking all day) so finally bothered to respond now. 

I had not meant to submit them to you. Just start practicing. Maybe submit something that worked to you, and then ask for more help and ideas and start sharing and contributing. But I'm not sure what to do. I do not know the pricess. I messed up with submitting my "randomly copied from notes into GitHub" to you before I really even bothered cloning the repo and testing the build... or whatever comes next. 

I learn by doing. I learn by mistakes. Maybe I could have found a different project to learn with, but until I saw panic-inducing emails, I thought this was the one.

**Comment by LinusDierheimer** [comment]
Pull request are there to discuss two things:
* If the intended change makes sense to have in the project
* How it was implemented: Bugs & Code style

A submission that doesn't compile or run is therefore out of scope, and usually closed without taking a closer look to the code. And this does happen annoyingly often. 

If you posted this by accident, fine. But be aware that we do this in our free time too. Personally for example, i spend my whole day at university and then give up some sleep to work on open source. I am sure you can understand why i have neither the energy nor the time to deal with pull requests that don't meet the criterias. What might seem rude or arrogant on the first glance is often just the fastes way to say everything relevant.

If you have a pull request, that does compile, run, and changes something sensefull, we are happy to do a proper code review.

For the beginning phase i have some tipps for you:
* Don't use OneNote or Notepad++ to write code. I am using VSCode.
* Start with a personal project on your personal GitHub to learn how git works.
* Test everying extensivly before submitting to another person, everyone will expect that from you.

**Comment by CarterLi** [comment]
All code you added is basically a copy of the original code, except a `free(pProcessorInfo);` right?

**Pull request closed without merging**
