### PR TITLE
Adding RebornOS to the supported logos

### PR DESCRIPTION
**Pull request by shivanandvp**
The current PR aims to add support for RebornOS' logo to fastfetch
Screenshot_20220308_110801

### CODE REVIEW

**Comment by shivanandvp** [comment]
Please feel free to replace it with a better logo if you can. I am not sure this is the best it can be. It could use improvement

**Comment by LinusDierheimer** [comment]
Is it intended, that the keys don't line up in a vertical line?
Usually i copy the logos from neofetch, so i'm sure i can't create a better one.

**Comment by shivanandvp** [comment]
@LinusDierheimer I could have it either line up or not. What do you prefer?

**Comment by LinusDierheimer** [comment]
line up, so it is consistent with all other logos (and fetch programs)

**Comment by LinusDierheimer** [comment]
LGTM

**Comment by shivanandvp** [comment]
Screenshot_20220308_113735

**Comment by shivanandvp** [comment]
Thanks 👍🏽

**Pull request merged**
