### PR TITLE
Media: support song detection on macOS

### PR DESCRIPTION
**Pull request by CarterLi**
Will do player tomorrow if I have time

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
I can't test it, but code wise it seems fine. Thanks a lot!

**Comment by LinusDierheimer** [comment]
I noticed that you used objective c, but i don't see anything that requires the use of it. Why not stay in c?

And is the media remote framework guaranteed to exist on MacOS? If yes we can just link against it.

**Comment by CarterLi** [comment]
> I noticed that you used objective c, but i don't see anything that requires the use of it. Why not stay in c?

using of `<CoreFoundation/CoreFoundation.h>` requires obj-c ( which is a obj-c header file )

Also notice the usage of `^` block syntax ( may also be provided as a C extension )

> 
> And is the media remote framework guaranteed to exist on MacOS?

Yes.

> If yes we can just link against it.

No. `/System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote` is a private framework, which cannot be directly linked against. `MediaRemote.framework` isn't in the framework search path, `-framework /System/Library/PrivateFrameworks/MediaRemote.framework` doesn't work and `MediaRemote.framework` provides no header files.

**Comment by LinusDierheimer** [comment]
Then i am completely fine with the current state.

**Pull request merged**
