### PR TITLE
tidy bios_linux.c

### PR DESCRIPTION
**Pull request by hilga007**
use logical negation (!) and replace the != true checks with || to be more concise and performant.

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
This doesn't make a difference.

**Comment by hilga007** [comment]
OK so do you mind explaining why? Again this was an accidental submition to you, but I have only been learning solo from a book with web UI for test items. 

According to the learning activities - yes, to the authors of the book  it does make a difference. The textbook states that || is more concise and performant and is best practice.

**Comment by LinusDierheimer** [comment]
An if stops evaluating as soon as the result is clear:
```c
//All must be true, so if b is false, c won't be evaluated, because the if will always be false
if(a && b && c) {}

//One must be true, so if a is false, and b is true, there is no reason to evaluate c anymore
if(a || b || c) {}
```
Usually you try to evaluate as little as possible, because that logically is more performant. What the better solution is depends on the situation, not the operator. Both are equally good.

Also readability is a factor. Code that can be easier read is usually better code.

**Comment by LinusDierheimer** [comment]
In this example both are virtually the same. Both stop as soon as possible. You can show this with boolean algebra:
```c
// de morgan's laws
!a && !b && !c = !(a || b || c)
```
But i think my solution is more readable.

**Pull request closed without merging**
