### PR TITLE
Release 1.8.1

### PR DESCRIPTION
**Pull request by CarterLi**

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
We should give credit to #365.

**Comment by CarterLi** [comment]
Done

**Comment by LinusDierheimer** [comment]
Is there a reason this was closed?

**Comment by LinusDierheimer** [comment]
@CarterLi I think we can do the release. Is there anything blocking it?

**Comment by CarterLi** [comment]
I was trying to build a Windows x86-32 binary, and encountered many problems.

I decided not to support Windows x32 version for now. Let's cut a release

**Pull request closed without merging**
