### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by CarterLi**
image

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
Can we strip `Apple` and `Intel` prefixes from the GPU name and set vendor accordingly? Would not only give a prettier output, but format strings would work better too.

Personally i would also remove the `Graphics` suffix.

**Comment by CarterLi** [comment]
Problem is that the string format returned is not guaranteed. What about AMD graphic cards?

**Comment by LinusDierheimer** [comment]
I would write code similar to this (don't blindly copy it, i am writing this directly on github):

```c
ffStrbufRemoveIgnCaseEndS(&name, "Graphics");
ffStrbufTrimRight(&name);

char intelPrefix[] = "AppleIntel";
char applePrefix[] = "Apple";

if(ffStrbufStartsWithIgnCaseS(&name, intelPrefix)
{
    ffStrbufSubstrAfter(&name, sizeof(intelPrefix);
    ffStrbufAppendS(&vendor, "Intel");
}
else if(ffStrbufStartsWithIgnCaseS(&name, applePrefix)
{
    ffStrbufSubstrAfter(&name, sizeof(applePrefix);
    ffStrbufAppendS(&vendor, "Apple");
}

ffStrbufTrimLeft(&name);
```

**Comment by CarterLi** [comment]
Updated, now we can correctly detect Intel Iris graphics

image

As for vendor, I don't think I want to do it before I can verify whether it works for other graphic cards.

**Comment by LinusDierheimer** [comment]
Thank you.

**Pull request merged**
