### PR TITLE
Add CentOS logo support

### PR DESCRIPTION
**Pull request by CarterLi**
Logo is used from neofetch

image

Also removes C++ compiler requirement in CMakeList as this project is a pure C project

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
Most of the spaces at EOL in the README are intentonal, as they mean linebreak in markdown.

**Comment by CarterLi** [comment]
My fault. I was auto formatted by vscode.

**Comment by CarterLi** [comment]
Fixed @LinusDierheimer

**Comment by LinusDierheimer** [comment]
Great, thank you. BTW you can install the editor config extension to almost any editor in existences, the .editorconfig prevents trimming trailing whitespaces from markdown files.

**Pull request merged**
