### PR TITLE
New Ubuntu logo

### PR DESCRIPTION
**Pull request by AloneER0**
Maybe it's not really a useful pull request but i would like to know what do you think about the new Ubuntu ascii from neofetch master 
image

There shouldn't be any build errors.

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
I like the new logo, and it makes sense to use it, as it resembles the new ubuntu logo. But can we keep the old logo as `ubuntu_old` around? Similar to what for example fedora has.

**Comment by AloneER0** [comment]
Oh yeah sure! i can bring back the old logo

**Comment by AloneER0** [comment]
Let me push the changes.
image

**Comment by LinusDierheimer** [comment]
Great, thank you!

**Comment by AloneER0** [comment]
I just realized it has some formatting errors..

**Comment by AloneER0** [comment]
let me correct them

**Pull request merged**
