### PR TITLE
Fixed removeStrings() divider

### PR DESCRIPTION
**Pull request by DarNCelsius**
remstrs3

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
This doesn't seem right at all, because `168 / (168 / 8)` is `8` while `168 / 8` is the correct amount of `21`. Does hard coding the this value work?

**Comment by DarNCelsius** [comment]
Hang on...

**Comment by DarNCelsius** [comment]
It alternates with different values. Removes 8-Core, but not Processor and vice versa.

**Comment by LinusDierheimer** [comment]
So the implementation is flawed. Time to look into it.

**Comment by DarNCelsius** [comment]
Using `ffStrbufRemoveStrings(&namePretty, 2, " Processor", " 8-Core");` fails - '8-core' is removed.
Using `ffStrbufRemoveStrings(&namePretty, 1, " Processor");` works.

**Comment by DarNCelsius** [comment]
All these functions end up in  `strbufRemoveTest()`. Is there a condition missing or something in there?

**Comment by DarNCelsius** [comment]
Manipulating `strbuf->length -= k;` with for example `strbuf->length -= k + 1;` on line 316, will change the output of the "Processor" string, so it's definitely passed both checks in the for loop.

**Comment by DarNCelsius** [comment]
Does the order in which the string elements are encountered matter?

Rearranging the array to this:
```c
    const char* removeStrings[] = {
        "(R)", "(r)", "(TM)", "(tm)",
        " Dual-Core", " Quad-Core", " Six-Core", " Eight-Core", " Ten-Core",
        " 2-Core", " 4-Core", " 6-Core", " 8-Core", " 10-Core", " 12-Core", " 14-Core", " 16-Core",
        " CPU", " FPU", " APU", " Processor"
    };
```
fixes it completely for me. This array order mimics the order in the original string - `AMD Ryzen 7 3800X 8-Core Processor`.
remstrs4
Both `8-Core` and `Processor` is removed. Not a proper fix, but should help track it down.

**Comment by DarNCelsius** [comment]
I opened an issue for this #47.

**Pull request closed without merging**
