### PR TITLE
Changed ffStrbufRemoveStringsA() iterator logic

### LINKED ISSUE #47: ffStrbufRemoveStrings() functions are order dependent
Original string: `AMD Ryzen 7 3800X 8-Core Processor`

With the current string array in `cpu.c`, `ffStrbufRemoveStringsA()` only removes `8-Core` in the above string:
```c
    const char* removeStrings[] = {
        "(R)", "(r)", "(TM)", "(tm)",
        " CPU", " FPU", " APU", " Processor",
        " Dual-Core", " Quad-Core", " Six-Core", " Eight-Core", " Ten-Core",
        " 2-Core", " 4-Core", " 6-Core", " 8-Core", " 10-Core", " 12-Core", " 14-Core", " 16-Core"
    };
```
Rearranging it to
```c
    const char* removeStrings[] = {
        "(R)", "(r)", "(TM)", "(tm)",
        " Dual-Core", " Quad-Core", " Six-Core", " Eight-Core", " Ten-Core",
        " 2-Core", " 4-Core", " 6-Core", " 8-Core", " 10-Core", " 12-Core", " 14-Core", " 16-Core",
        " CPU", " FPU", " APU", " Processor"
    };
```
removes the proper strings.
```c
ffStrbufRemoveStrings(&namePretty, 2, " Processor", " 8-Core");
```
 removes `8-Core`
```c
ffStrbufRemoveStrings(&namePretty, 2, " 8-Core", " Processor");
```
 removes `8-Core` and `Processor`

### PR DESCRIPTION
**Pull request by DarNCelsius**
Fixes #47

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
I don't know why this fixes it but if it does i am happy.

**Comment by DarNCelsius** [comment]
It changes the outer loop to iterate through the number of elements to remove. Seemed backwards before.
I'm still not experienced enough to fully understand the inner portions and `strbufRemoveTest()` though.

**Comment by DarNCelsius** [comment]
Is it still working okay in your end?

**Comment by LinusDierheimer** [comment]
Its is.

**Comment by DarNCelsius** [comment]
Tested on Void with my i7-3930K, and the output is the same as with r254.

**Pull request merged**
