### PR TITLE
Fix GPU value not showing up correctly

### PR DESCRIPTION
**Pull request by saloniamatteo**
From #9: added `ctags` & `cscope` files to `.gitignore`

New: memory usage is the same (`128` in the previous PR, `64` now).

When reading from fd (file descriptor) with `read()`, rewind fd by 1.
If the return value of `read()` is 0, we have reached the end of the file (`EOF`),
as stated in `man 2 read`:

```
On success, the number of bytes read is returned
(zero indicates end of file),
and the file position is advanced by this number.
```

This PR fixes issue #8 at LinusDierheimer/fastfetch.

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
This doesn't rewind the file but just makes fd pointing to another position im memory, which may even be another file. I already have implemented the right behaviour and after short testing i will commit. Thanks for the effort

**Comment by saloniamatteo** [comment]
OK. Can you at least add those changes made to `.gitignore` on my behalf?

**Comment by LinusDierheimer** [comment]
This is done.

**Comment by saloniamatteo** [comment]
Thanks.

**Pull request closed without merging**
