### PR TITLE
Update help.txt

### PR DESCRIPTION
**Pull request by kojq**
Also, consider changing `--disable-linewrap` to `--disable-line-wrap`.

### CODE REVIEW

**Comment by kojq** [comment]
This resolves #354

**Comment by kojq** [comment]
I did some cleanup. Also, gotta remove this if #352 comes through:
```
    -r,--recache <?value>:            Generate new cached values
    --nocache <?value>:               Don't use cached values, but also don't overwrite existing ones
```

**Comment by kojq** [comment]
For binary choices, the word choice is inconsistent. Is `whether` or `set if` preferred?

**Comment by kojq** [comment]
Superfluous and ambiguous language have been removed.

**Comment by kojq** [comment]
Some different mistakes are in `/src/data/config_user.txt`. Should that file be changed separately because it is a bit long and shares some information with `/src/data/help.txt` as well?

**Comment by LinusDierheimer** [comment]
Thanks for your work on this. Feel free to add other help files to this PR too!

> For binary choices, the word choice is inconsistent.

Choose what sounds better to you. I'm not a native speaker, so i can' really tell.

**Pull request merged**
